//
// CounterRPCService.swift
// NativeRPC Flutter Example
//
// Counter service implementation using the NativeRPC Params pattern.
// Based on code generated by NativeRPC Code Generator.
//

import NativeRPCKit

/// CounterStats - Counter statistics
struct CounterStats: Codable, Sendable {
    let incrementCount: Double
    let decrementCount: Double
    let peakValue: Double
    let lowestValue: Double
}

/// CounterResult - Counter operation result
struct CounterResult: Codable, Sendable {
    let value: Double
    let timestamp: Double
    let operation: CounterOperation
}

/// CountChangedPayload - Payload for count changed events
struct CountChangedPayload: Codable, Sendable {
    let previousValue: Double
    let newValue: Double
    let operation: CounterOperation
}

/// ResetPayload
struct ResetPayload: Codable, Sendable {
    let previousValue: Double
}

/// ErrorPayload
struct ErrorPayload: Codable, Sendable {
    let code: String
    let message: String
}

/// CounterOperation - Types of counter operations
enum CounterOperation: String, Codable, Sendable {
    case increment = "increment"
    case decrement = "decrement"
    case add = "add"
    case reset = "reset"
}

/// Counter Service
/// 
/// A simple counter service demonstrating NativeRPC capabilities.
/// Supports both synchronous and asynchronous operations.
final class CounterRPCService: NativeRPCService, @unchecked Sendable {

    // MARK: - Service Registration
    
    /// The unique service name for registration
    override class var serviceName: String { "counter" }
    
    // MARK: - State
    
    /// The current counter value
    private var count: Double = 0
    
    /// Statistics tracking
    private var incrementCount: Double = 0
    private var decrementCount: Double = 0
    private var peakValue: Double = 0
    private var lowestValue: Double = 0
    
    // MARK: - Initialization
    
    /// Create a new instance with the given context
    required init(context: NativeRPCContext?) {
        super.init(context: context)
    }

    // MARK: - Service Definition
    
    @ServiceDefinitionBuilder
    override func definition() -> ServiceDefinitionContainer {
        // Note: Name is auto-set from serviceName class property
        
        // Get the current counter value
        Function("getValue") { [weak self] () -> Double in
            self?.count ?? 0
        }
        
        // Increment the counter by 1
        Function("increment") { [weak self] () -> Double in
            guard let self = self else { return 0 }
            let previousValue = self.count
            self.count += 1
            self.incrementCount += 1
            self.updatePeakAndLowest()
            self.emitCountChanged(CountChangedPayload(
                previousValue: previousValue,
                newValue: self.count,
                operation: .increment
            ))
            return self.count
        }
        
        // Decrement the counter by 1
        Function("decrement") { [weak self] () -> Double in
            guard let self = self else { return 0 }
            let previousValue = self.count
            self.count -= 1
            self.decrementCount += 1
            self.updatePeakAndLowest()
            self.emitCountChanged(CountChangedPayload(
                previousValue: previousValue,
                newValue: self.count,
                operation: .decrement
            ))
            return self.count
        }
        
        // Add a value to the counter
        Function("add") { [weak self] (params: AddParams) -> Double in
            guard let self = self else { return 0 }
            let previousValue = self.count
            self.count += params.value
            self.updatePeakAndLowest()
            self.emitCountChanged(CountChangedPayload(
                previousValue: previousValue,
                newValue: self.count,
                operation: .add
            ))
            return self.count
        }
        
        // Add two values to the counter
        Function("addTwo") { [weak self] (params: AddTwoParams) -> Double in
            guard let self = self else { return 0 }
            let previousValue = self.count
            self.count += params.a + params.b
            self.updatePeakAndLowest()
            self.emitCountChanged(CountChangedPayload(
                previousValue: previousValue,
                newValue: self.count,
                operation: .add
            ))
            return self.count
        }
        
        // Reset the counter to zero
        Function("reset") { [weak self] () -> Double in
            guard let self = self else { return 0 }
            let previousValue = self.count
            self.count = 0
            self.incrementCount = 0
            self.decrementCount = 0
            self.peakValue = 0
            self.lowestValue = 0
            self.emitReset(ResetPayload(previousValue: previousValue))
            return self.count
        }
        
        // Get counter statistics
        Function("getStats") { [weak self] () -> CounterStats in
            guard let self = self else {
                return CounterStats(incrementCount: 0, decrementCount: 0, peakValue: 0, lowestValue: 0)
            }
            return CounterStats(
                incrementCount: self.incrementCount,
                decrementCount: self.decrementCount,
                peakValue: self.peakValue,
                lowestValue: self.lowestValue
            )
        }
        
        // Get value with simulated network delay
        AsyncFunction("getValueDelayed") { [weak self] (params: GetValueDelayedParams) async throws -> Double in
            try await Task.sleep(nanoseconds: UInt64(params.delayMs) * 1_000_000)
            return self?.count ?? 0
        }
        
        // Perform an async add operation
        AsyncFunction("addAsync") { [weak self] (params: AddAsyncParams) async throws -> CounterResult in
            guard let self = self else {
                throw NativeRPCError.internalError("Service not available")
            }
            
            // Apply delay if specified
            if let delayMs = params.delayMs {
                try await Task.sleep(nanoseconds: UInt64(delayMs) * 1_000_000)
            }
            
            let previousValue = self.count
            self.count += params.value
            self.updatePeakAndLowest()
            self.emitCountChanged(CountChangedPayload(
                previousValue: previousValue,
                newValue: self.count,
                operation: .add
            ))
            
            return CounterResult(
                value: self.count,
                timestamp: Date().timeIntervalSince1970 * 1000,
                operation: .add
            )
        }
        
        // Divide the current value (demonstrates error handling)
        AsyncFunction("divideBy") { [weak self] (params: DivideByParams) async throws -> Double in
            guard let self = self else { return 0 }
            
            if params.divisor == 0 {
                self.emitError(ErrorPayload(code: "DIVIDE_BY_ZERO", message: "Cannot divide by zero"))
                throw NativeRPCError.invalidParams("Cannot divide by zero")
            }
            
            // Simulate some async work
            try await Task.sleep(nanoseconds: 100_000_000) // 100ms
            
            return self.count / params.divisor
        }
        
        // Fetch and apply a remote value
        AsyncFunction("fetchRemoteValue") { [weak self] () async throws -> CounterResult in
            // Simulate network delay
            try await Task.sleep(nanoseconds: 500_000_000) // 500ms
            
            let currentValue = self?.count ?? 0
            
            return CounterResult(
                value: currentValue * 2,
                timestamp: Date().timeIntervalSince1970 * 1000,
                operation: .add
            )
        }
        
        // Event: Emitted when the counter value changes
        Events("countChanged")
        
        // Event: Emitted when the counter is reset
        Events("reset")
        
        // Event: Emitted when an error occurs
        Events("error")
        
        // Lifecycle hooks
        OnCreate {
            print("[CounterRPCService] Service created")
        }
        
        OnDestroy {
            print("[CounterRPCService] Service destroyed")
        }
    }
    
    // MARK: - Helper Methods
    
    private func updatePeakAndLowest() {
        if count > peakValue {
            peakValue = count
        }
        if count < lowestValue {
            lowestValue = count
        }
    }
    
    // MARK: - Event Emitters
    
    /// Emit countChanged event
    func emitCountChanged(_ payload: CountChangedPayload) {
        emit("countChanged", data: payload)
    }
    
    /// Emit reset event
    func emitReset(_ payload: ResetPayload) {
        emit("reset", data: payload)
    }
    
    /// Emit error event
    func emitError(_ payload: ErrorPayload) {
        emit("error", data: payload)
    }
    
}
