//
// AUTO-GENERATED FILE - DO NOT MODIFY
// Generated by NativeRPC Code Generator
// Source: services.ts
// Generated at: 2026-02-02T04:09:45.550Z
//
// This file contains Codable Params types for the service.
// These types are used for strongly-typed parameter decoding in RPC functions.
//

import Foundation

// MARK: - CounterRPCService Params Types

extension CounterRPCService {
    
    /// Parameters for `add` method
    struct AddParams: Codable {
        let value: Double
    }
    
    /// Parameters for `addTwo` method
    struct AddTwoParams: Codable {
        let a: Double
        let b: Double
    }
    
    /// Parameters for `getValueDelayed` method
    struct GetValueDelayedParams: Codable {
        let delayMs: Double
    }
    
    /// Parameters for `addAsync` method
    struct AddAsyncParams: Codable {
        let value: Double
        let delayMs: Double?
    }
    
    /// Parameters for `divideBy` method
    struct DivideByParams: Codable {
        let divisor: Double
    }
    
}
